### ISSUE TITLE
List of records doesn't refresh when moving between two models of the same type

### ISSUE THREAD

**Issue by camdendotlol** [performant-software/core-data-cloud#141]
Steps to replicate:

1. Create two models in a project of the same type (i.e. both Works, both People, etc.)
2. Populate them with some data.
3. Move between the two models using the dropdown.
4. The list won't refresh. It seems to be fetching the data, but the UI doesn't change.

I think there might be some caching logic that assumes that every model has a different type - maybe a `key` prop somewhere?

Some existing examples on staging right now:

1. Documents and Jobs in the NBU project (both are Works)
2. Archives and Publishers in Bischoff (both are Organizations)

**Comment by SteveMarvin** [comment]
First note is that it is still not auto-refreshing when creating a new model. I have to manually refresh to see the new model in the dropdown.

**Comment by SteveMarvin** [comment]
On the core data item about lists refreshing, I am getting a partial refresh, but not complete. Or something like that. I have a second Person group (People 2) with a Peter record and a Paul record. however, when I switch to it from People 1 I get a list with two Peters.
![image](https://github.com/performant-software/core-data-cloud/assets/18423533/794b6529-0c46-40c7-a544-3a8daa3fb305)

A manual refresh does NOT fix it.



But if I click into one of the Peters to edit, I see the Paul record again
![image](https://github.com/performant-software/core-data-cloud/assets/18423533/32a97adf-0250-44ee-82c3-ca92f8e7e05b)

**Comment by SteveMarvin** [comment]
Never mind, I added Paul as another primary incorrectly into Peter, not as itself. This bug is fixed, but the ability to add two primaries to a single record will be added as a New Issue.
