### ISSUE TITLE
Merge Records

### ISSUE THREAD

**Issue by dleadbetter** [performant-software/core-data-cloud#205]
As a data entry user, I want to assert two records of the same type are the same and merge them together.

- Allow users to resolve conflicts on base record
- Union all relationships that are not "duplicates"
	- A duplicate relationship will be defined as a relationship where the primary and related records are the same and any/all user-defined fields have the same value

###### Implementation
Allow the user to select two records and elect to merge them. The client will make a request for Record A and Record B and display a dialogue comparing the fields (on the base record) between the two. Users will be allowed to select which field(s) from each record they wish to persist in the new merged record.

The user will then confirm the merge. The client will make a request to a new `/merge` endpoint with the IDs for Record A and Record B, along with the selected field values for the merged record. The endpoint will update Record A with the new field values, move any non-duplicate relationships from Record B to Record A, and delete Record B.

**Comment by dleadbetter** [comment]
Tagging @NickLaiacona and @camdendotlol for comments on requirements and implementation.

**Comment by camdendotlol** [comment]
This looks good to me.

**Comment by NickLaiacona** [comment]
Regarding duplicate relationships, two relationships might have the same objects on either end but might be joined with different data, such as the XML ID in the case of NBU. If the join data is different, we need a way to combine the join data in order to create a single relationship that preserves all the XML IDs.

**Comment by dleadbetter** [comment]
> Regarding duplicate relationships, two relationships might have the same objects on either end but might be joined with different data, such as the XML ID in the case of NBU. If the join data is different, we need a way to combine the join data in order to create a single relationship that preserves all the XML IDs.

Right, my plan is to do the Merge Record (#205) feature first, then implement the Re-import from FairCopy.cloud (#206) feature. I think this will likely be part of #206 as we won't need or have the XML ID columns for this feature.
