### ISSUE TITLE
Re-import from FairCopy.cloud

### ISSUE THREAD

**Issue by dleadbetter** [performant-software/core-data-cloud#206]
As a data entry user, I want to re-import an updated document from FairCopy.cloud (represented as an `items` record in CoreData).

- Allow users to resolve conflicts on base record
- Allow users to resolve conflicts on relationships and related records
- Maintain list of FairCopy.cloud `XML_ID` values on relationships
	- Update "Merge Records" process above to maintain `XML_ID` values on relationships

###### Implementation
I'm not yet entirely sure how to implement this, but have a basic idea:
- User initiates import from `items` edit page; `.zip` file containing `.csv` files is retrieved from FairCopy.cloud
- We essentially allow the user to modify the `.csv` files in order to resolve conflicts
- Compress the `.csv` files into a `.zip` and import the modified files

**Comment by dleadbetter** [comment]
Tagging @NickLaiacona and @camdendotlol for comments on requirements and implementation.

**Comment by camdendotlol** [comment]
This looks good.

I think the CSV generation script on FCC and CD's import service will both need to be updated to pull in the XML ID of each imported record. Currently the FCC parser generates one UUID per matching element and uses it for both the XML ID of the element and for the UUID of the record it adds to the CSV file. But if we're merging records, their XML IDs might no longer match their UUIDs. So Core Data will need a way to know the XML ID of a record in a given document so it can store it on the relation.

**Comment by dleadbetter** [comment]
## Testing/Setup Instructions

### FairCopy.cloud
1. Connect FairCopy to an ArchivEngine project
2. Check out a document, check the document back in
	1. This will generate the `zip` file needed by Core Data
3. Publish the document

### Core Data
1. Create an "Item" model that will serve as the record used to import data
2. In "Project Settings" mode, set the FairCopy.cloud URL and FairCopy.cloud connected model
	1. Use https://staging.faircopy.cloud as the FairCopy.cloud URL
	2. Use the newly created "Item" model as the FairCopy.cloud connected model
3. In "Data Entry" mode, navigate to the list for the "Item" model and add a new record
	1. In the "FairCopy.cloud Identifier" field, enter the XML_ID of the record in FairCopy.cloud
4. Use the import button to view the incoming changes and resolve any conflicts

**Comment by dleadbetter** [comment]
@SteveMarvin - I've setup this record to so that it will successfully import from FairCopy.cloud, so you can bypass the setup instructions above: https://core-data-cloud-staging-2c51db0617a5.herokuapp.com/projects/22/132/108521

Testing should include verifying the import works, changing some data (merging records) and re-importing.

**Comment by SteveMarvin** [comment]
Re-import does not seem to restore deleted records. See example of Georgio de marlio.

Also, deleting all records from a dropdown page causes an error on import
![image](https://github.com/performant-software/core-data-cloud/assets/18423533/f713426e-f714-430e-bacf-f4d6a167ce71)
