### ISSUE TITLE
Relationship Descriptors

### ISSUE THREAD

**Issue by dleadbetter** [performant-software/core-data-cloud#214]
Currently when viewing a list of related records (e.g `/public/people/:uuid/people`) there isn't a good way to tell how the relationship should be described. This issue is particularly apparent when the related model and the primary model are of the same type and the relationship needs to be viewed in both directions.

- [ ] Add the `inverse_name` attribute to the `/public/project/:id/descriptors` endpoint
- [ ] Add the `project_model_relationship_uuid` to the `/public/*/:uuid/*` endpoints
- [ ] Add the `inverse` indicator to the `/public/*/:uuid/*` endpoints

**Comment by dleadbetter** [comment]
Tagging @ajolipa to review.

**Comment by ajolipa** [comment]
This sounds perfect to me!

**Comment by dleadbetter** [comment]
Tested on NBU. Closing.
