### ISSUE TITLE
Shared Model Labels

### ISSUE THREAD

**Issue by dleadbetter** [performant-software/core-data-cloud#223]
Update the shared model labels in the list view to be more clear:

<img width="865" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekJOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d4df2c6739b1eacef894cc5915c77c23175ddcf/Screenshot%202024-06-10%20at%2010.54.21%E2%80%AFAM.png" alt="Screenshot 2024-06-10 at 10.54.21 AM.png" />

E.g.

All Villes >> All Villes
Shared Villes >> Villes Shared by Other Projects [Maybe: ___ From other projects]
My Villes >> Villes from “Project Name”

**Comment by dleadbetter** [comment]
@jamiefolsom - Thoughts on the UI? I think it might get a little wordy depending on the name of the model/project.

![Screenshot 2024-06-10 at 2 40 46 PM](https://github.com/performant-software/core-data-cloud/assets/20641961/cc2ba600-cf2d-469b-8687-0e61eb3ce100)

**Comment by jamiefolsom** [comment]
Definitely gets long, but I think it's ok -- it's clear. The only other option might be "____ from **this** project" vs "____ from **other** projects". Does that seem unambiguous to you?

**Comment by dleadbetter** [comment]
We also have a similar menu when adding a relationship between models.

![Screenshot 2024-06-11 at 6 05 59 AM](https://github.com/performant-software/core-data-cloud/assets/20641961/eeba3455-0d00-43be-b6aa-88333982d4e1)

**Comment by dleadbetter** [comment]
I think this option is probably the safest. It contains the same amount of variability as before (just the model name), and I think it's unambiguous enough.

![Screenshot 2024-06-11 at 9 13 11 AM](https://github.com/performant-software/core-data-cloud/assets/20641961/56c958f7-9b51-4f1c-ba4a-4df781e110fb)

![Screenshot 2024-06-11 at 9 12 57 AM](https://github.com/performant-software/core-data-cloud/assets/20641961/712b0bcf-2673-4cad-9e7f-1ec674ea02dd)
