### ISSUE TITLE
Edit/Settings views

### ISSUE THREAD

**Issue by dleadbetter** [performant-software/core-data-cloud#227]
- Currently, these are called “Settings” and “Edit”
- We should call them “Data Entry” mode, and “Project Settings” Mode
- Both modes should be visible at top right at all times
- These could be tabs or something similar; 
- The current one should appear active; the non-current one available.
- We might go further, and make the blue bar black in Data Modeling Mode (or give it a different background pattern, or something very visible).

<img width="304" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2300c012da1e7cefcd1ef27e183cec6e11a67bfe/Screenshot%202024-06-10%20at%203.44.33%E2%80%AFPM.png" alt="Screenshot 2024-06-10 at 3.44.33 PM.png" />

**Comment by dleadbetter** [comment]
@jamiefolsom - Thoughts?

![Screenshot 2024-06-10 at 3 53 43 PM](https://github.com/performant-software/core-data-cloud/assets/20641961/217f16cb-5edd-4081-9f24-2a0e50a687ac)

**Comment by jamiefolsom** [comment]
I think that darker background on the active mode works -- is there a hover state on the inactive mode button?

**Comment by dleadbetter** [comment]
Yes, also the darker background.

![Screenshot 2024-06-11 at 5 51 22 AM](https://github.com/performant-software/core-data-cloud/assets/20641961/6d6a4873-4924-4cc3-8e72-66645a934a64)
