### ISSUE TITLE
Image thumbnails on Company Towns

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/core-data-cloud#251]
Last week, I did a test to re-import images whose thumbnails did not appear, and everything worked. 

However, as I continue the work today, I realize that the problem has returned, at least for certain cities. For example, the thumbnails of the photos of the town of Siedlung Eisenheim that I download do not appear, while those of Margaratenhohe are visible.

In addition, when I download photos of the town of Crespi d'Adda, only certain images appear in the icon library (e.g. files IMGP0419 and 422 are visible, but not files IMGP0420 and 421).

I will send you a sample of photos of these cities via WeTransfer. Is the problem with the files themselves?

[JF NOTE] I will share sample image files separately.

**Comment by dleadbetter** [comment]
@jamiefolsom - It looks like the Sidekiq worker for the `iiif-cloud-uqam` instance was turned off. So images were not correctly being converted to pyramid TIFFs to be served by the IIIF server. I've turned the worker back on and converted all of the images that had not been converted automatically. Moving forward, this should work automatically.
