### ISSUE TITLE
Events Model

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/core-data-cloud#27]
### Events
- Data model
- API
- Admin UI
- Public UI for one event
- Public UI for all events linked to another record
- Search controls and visualization display

**Data Model, API, Admin UI**
- [ ] Plain english descriptors
  - [ ] "Period of time during which thing happened" would have a start (fuzzy) date and an end (fuzzy) date, each with its own plain language descriptor, and with either a specific date (or year/month or just year) or a range of dates.
  - [ ] "Approximate date on which something happened" would have a (fuzzy) date, with a plain language descriptor, and with either a specific date (or year/month or just year) or a range of possible fuzzy dates.
  - [ ] "Date on which something happened" would have a (fuzzy) date, with a plain language descriptor, and with a specific date, whether dd/mm/yy or mm/yy or yy.
- [ ] Fuzzy Dates (with all of their features)
  - [ ] In the db, an FD is either one or two specific dates, plus a plain language descriptor.
- [ ] Relatable to other core data models

**Public UI**
- Time-based search facet: [instantsearch range slider widget](https://instantsearchjs.netlify.app/stories/js/?path=/story/refinements-rangeslider--default)
- Per-record timeline viewer: consider using [Tailwind Feed Component](https://tailwindui.com/components/application-ui/lists/feeds)

### Project UI Screenshots
- NBU: <img width="711" alt="Screen Shot 2024-03-11 at 15 07 57" src="https://github.com/performant-software/core-data-cloud/assets/882377/44b7fb21-a586-4e23-afb9-1a66323d2721">

**Comment by dleadbetter** [comment]
Events Data Model

![Screenshot 2024-04-16 at 11 19 55 AM](https://github.com/performant-software/core-data-cloud/assets/20641961/aa10bc61-f462-40d1-adcf-c9e8858d899c)
