### ISSUE TITLE
Import Dialog Sort Table by Columns

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/core-data-cloud#271]
Folks from NBU are asking if we can sort the rows in the import dialog by column. They especially want to sort by name, so that they can quickly scan for duplicate entries.

![Screenshot 2024-08-14 163548](https://github.com/user-attachments/assets/d9c0072e-a267-419a-9a24-8bf933b09378)

**Comment by dleadbetter** [comment]
@NickLaiacona - During our discussion of this feature for SJP, we determined that hard-coding a sort by `name` was probably sufficient (as opposed to allowing the user to click a column to sort). Will that behavior also serve NBU's use case?

**Comment by NickLaiacona** [comment]
Yes, that's right! That should work.
