### ISSUE TITLE
Images not loading reliably

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/core-data-cloud#297]
For the thumbnail, the page appears to be trying to load default.jpg, with content type text/plain, and getting a 500 error:

<img width="1597" alt="Screen Shot 2024-09-18 at 17 42 16" src="https://github.com/user-attachments/assets/6195e088-c86f-48d8-8461-e14e5d442cf3">

For the full size "view image" button, it's loading the file by its filename, DSC01858.JPG, which works:

<img width="1597" alt="Screen Shot 2024-09-18 at 17 43 37" src="https://github.com/user-attachments/assets/e14ff6b2-9967-44d5-817e-29408e130adb">

Cantaloupe logs show this, around the same time:

```
Sep 18 21:45:21 cantaloupe-iiif-production bash[2955759]: 21:45:21.809 [qtp1617550160-6503] DEBUG e.i.l.c.r.ImageRequestHandler - Format inferred by unknown processor disagrees with the one supplied by >
Sep 18 21:45:21 cantaloupe-iiif-production bash[2955759]: 21:45:21.809 [qtp1617550160-6503] INFO  e.i.l.c.r.ErrorResource - Handling GET /iiif/3/2diwtn5oeiboc9hjorir9dg3mf39/square/%5E!250,250/0/default>
Sep 18 21:45:21 cantaloupe-iiif-production bash[2955759]: 21:45:21.809 [qtp1617550160-6503] DEBUG e.i.l.c.r.ErrorResource - Request headers: Accept: image/avif,image/webp,image/apng,image/svg+xml,image/>
Sep 18 21:45:21 cantaloupe-iiif-production bash[2955759]: 21:45:21.810 [qtp1617550160-6503] DEBUG e.i.l.c.r.ErrorResource - Base URI assembled from X-Forwarded headers: https://iiif.archivengine.com
Sep 18 21:45:21 cantaloupe-iiif-production bash[2955759]: 21:45:21.810 [qtp1617550160-6503] DEBUG e.i.l.c.r.HandlerServlet - Responded to GET /iiif/3/2diwtn5oeiboc9hjorir9dg3mf39/square/^!250,250/0/defa>
```

**Comment by jamiefolsom** [comment]
More detail, from the client:

> When importing, some photos upload without any problem, while for others, the thumbnail is always "broken". Quickly, I have the impression that it is the photos ending in ".jpg" (in lowercase), like the city of Paranapiabaca, that are causing the problem, while those ending in ".JPG" (in uppercase), like Calico, work. I admit that I don't really understand; I imagine that we can discuss it with Jamie.
> 
> For the annotation, doing it directly from the image library effectively solves the problem of going back and forth between pages. On the other hand, since the file names are not evocative, it is difficult to find your way around when you want to annotate a particular city.
> 
> However, I have a solution that, although a bit long, seems to work (tested with the city of Paranapiabaca). It would involve adding the name of the city to the names of the files themselves. It is then possible to filter the photos of the city alone. There would be another more technical solution, that is that the search engine of the image library allows to search not only in the names of files, but also in the fields of the photos, because they were associated with a city when they were downloaded. What do you think?

**Comment by dleadbetter** [comment]
It looks like the image was uploaded successfully, but not converted to a PTIF successfully. Requests for the images via Cantaloupe returned a 501 error because it was attempting to process the raw source image at request time and unable to (likely due to the size or type of image).

Viewing the image via the "View Image" button worked because that is being served directly from the IIIF Cloud Rails application.

I was able to get the image to load by converting the uploaded source image to PTIF, but the question still remains, why didn't it get converted when it was uploaded?

1. Do we know how these images are being uploaded? From where in the application? As single images? As a batch?
2. Is this issue happening for any other images?

**Comment by dleadbetter** [comment]
It looks like we're running into two separate issues here with images.

## Images not converted to PTIF
Some images were not converted to PTIFs upon upload. These images can be converted by running the `iiif:convert_images_empty` rake task, but it would be helpful to know how these records were added in the first place. See questions below.

[resources-without-converted-content.csv](https://github.com/user-attachments/files/17118390/resources-without-converted-content.csv)

## Images with `0` size content
Some images appear to have been uploaded "empty", meaning the file size is `0` bytes. These images will need to be re-uploaded, but it would be helpful to know how these records were added in the first place. See questions below.

[resources-with-empty-content.csv](https://github.com/user-attachments/files/17118393/resources-with-empty-content.csv)

## Questions
1. Where in the application are images being uploaded?
2. If batch uploading, how many images are contained in a batch?
3. If batch uploading, could we get a sample of a batch that produced these records?

**Comment by jamiefolsom** [comment]
Answers to your questions, @dleadbetter: 

- Where in the app do you usually download the images? 
> I upload the images on each city's record, in the "Nouveau Iconotheque" section.
- If you are uploading in bulk, how many images are in a group? 
> It varies greatly. Some cities have only about ten photos, while others have a few hundred.
- If you are uploading in bulk, could we get a sample from a group that produced these files? 
> I will send you the photos from the city of Zollverein in a separate email, via WeTransfer. 
> By the way, when I look at the city's record, only a minority of thumbnails are displayed correctly.

**Comment by dleadbetter** [comment]
@jamiefolsom - I tested the batch of Zollverein images you provided on staging and all images appear to have uploaded successfully: https://staging.coredata.cloud/projects/4/3/115829.

Is it possible this is some sort of network connection issue? At this point, I'm not really sure what else to test to reproduce the issue.

**Comment by jamiefolsom** [comment]
Hm, ok -- did you upload all 100 as a batch, or in smaller batches?

**Comment by dleadbetter** [comment]
> Hm, ok -- did you upload all 100 as a batch, or in smaller batches?

All of them as a single batch. All of the requests to upload the images completed successfully and the images were visible via IIIF after a few seconds.

**Comment by jamiefolsom** [comment]
Ok great. I will let them know and see if they can shed any more light on how they tried to do these uploads. Thanks!
